name: empowerment
channels:
  - defaults
dependencies:
  - pip:
    - appnope==0.1.0
    - backcall==0.1.0
    - cloudpickle==1.2.2
    - decorator==4.4.1
    - future==0.18.2
    - gym==0.15.4
    - ipdb==0.12.3
    - ipython==7.10.2
    - ipython-genutils==0.2.0
    - jedi==0.15.2
    - opencv-python==4.1.2.30
    - parso==0.5.2
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.2
    - ptyprocess==0.6.0
    - pyglet==1.3.2
    - pygments==2.5.2
    - scipy==1.4.1
    - traitlets==4.3.3
    - wcwidth==0.1.7

